# -*- coding: utf-8 -*-
"""EX1_impulse_noise_UQ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mG53QuzQXXrUcOAvOhJKiFDP4MYuES-T
"""

pip install optuna

import os, math, random, time
from google.colab import files
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.autograd as autograd
try:
    import optuna
except ImportError:
    raise ImportError("Please `pip install optuna` to run the hyperparameter search.")

pip install --force-reinstall sympy==1.13.3

import numpy as np, random, math
import torch, torch.nn as nn
import torch.optim as optim
import torch.autograd as autograd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401
from matplotlib import cm

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {DEVICE}")

### -------------------------------
### Problem setup (ODE: y'=-k y, y(0)=y0)
### -------------------------------
k, y0 = 2.0, 1.5
T0, T1 = 0.0, 1.0
N_TRAIN = 100
N_COL   = 256

def exact_np(t):
    return y0 * np.exp(-k * t)

##### Eval grid
t_eval_np = np.linspace(T0, T1, 200)
t_eval = torch.tensor(t_eval_np, dtype=torch.float32, device=DEVICE).reshape(-1,1)
y_true_np = exact_np(t_eval_np)

### -------------------------------
### (IMPULSE NOISE / OUTLIERS)
### -------------------------------
CORRUPTION_RATE = 0.0
IMPULSE_FACTOR  = 0.0

### -------------------------------
### Hyperparameters
### -------------------------------
MAX_EPOCHS = 1000
PATIENCE   = 20
MIN_DELTA  = 1e-4

HIDDEN_LAYERS = 2
HIDDEN_WIDTH  = 64
ACT           = "tanh"

LR = 1e-3
WD = 0.0

LAMBDA_IC   = 1.0
LAMBDA_PDE  = 1.0
LAMBDA_DATA = 1.0

P_RANGE = (0.2, 0.5)
T_MC    = 1000
M_BAG   = 20

### -------------------------------
### Data generator (DYNAMIC IMPULSE NOISE)
### -------------------------------
def make_dataset():
    t_np = np.linspace(T0, T1, N_TRAIN)
    y_clean = exact_np(t_np)
    y_np = y_clean.copy()

    if CORRUPTION_RATE > 0:
        max_y = np.max(np.abs(y_clean))
        actual_impulse_mag = IMPULSE_FACTOR * max_y

        n_corrupt = int(N_TRAIN * CORRUPTION_RATE)
        corrupt_idx = np.random.choice(N_TRAIN, n_corrupt, replace=False)
        signs = np.random.choice([-1.0, 1.0], size=n_corrupt)
        y_np[corrupt_idx] = signs * actual_impulse_mag

    t = torch.tensor(t_np, dtype=torch.float32, device=DEVICE).reshape(-1,1)
    y = torch.tensor(y_np, dtype=torch.float32, device=DEVICE).reshape(-1,1)
    return t, y

IC_t = torch.zeros((1,1), dtype=torch.float32, device=DEVICE)
IC_y = torch.tensor([[y0]], dtype=torch.float32, device=DEVICE)

def bootstrap(t, y):
    n = len(t)
    idx = np.random.choice(n, size=n, replace=True)
    return t[idx], y[idx]

def make_collocation_fixed(n_col=N_COL):
    return (torch.rand((n_col,1), device=DEVICE) * (T1 - T0) + T0)

### -------------------------------
### Models & UQ
### -------------------------------
def act(name):
    return {"tanh": nn.Tanh(), "relu": nn.ReLU(), "gelu": nn.GELU(), "silu": nn.SiLU()}[name]

class MLP(nn.Module):
    def __init__(self, in_dim=1, out_dim=1, L=HIDDEN_LAYERS, W=HIDDEN_WIDTH, act_name=ACT):
        super().__init__()
        A = act(act_name)
        layers = [nn.Linear(in_dim, W), A]
        for _ in range(L-1):
            layers += [nn.Linear(W, W), A]
        layers += [nn.Linear(W, out_dim)]
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)

class TestTimeBernoulliUQ(nn.Module):
    def __init__(self, core: nn.Sequential):
        super().__init__()
        self.core = core
        self.p = 0.3

    def set_p(self, p):
        self.p = float(p)

    def forward(self, x):
        out = x
        for m in self.core:
            out = m(out)
            if isinstance(m, (nn.Tanh, nn.ReLU, nn.GELU, nn.SiLU)):
                msk = (torch.rand_like(out) > self.p).float()
                out = out * msk / (1.0 - self.p + 1e-12)
        return out

### -------------------------------
### Losses & EarlyStopping
### -------------------------------
mse = nn.MSELoss()

def nn_loss(model, t, y):
    return mse(model(t), y)

def pinn_residual(model, t):
    t.requires_grad_(True)
    y = model(t)
    dy = autograd.grad(y, t, torch.ones_like(y), create_graph=True)[0]
    return dy + k * y

def pinn_total_loss_fixed(model, t, y, t_col_fixed):
    l_data = mse(model(t), y)
    l_ic   = mse(model(IC_t), IC_y)
    res    = pinn_residual(model, t_col_fixed.requires_grad_(True))
    l_pde  = torch.mean(res**2)
    return LAMBDA_DATA * l_data + LAMBDA_IC * l_ic + LAMBDA_PDE * l_pde

class ES:
    def __init__(self, patience=PATIENCE, min_delta=MIN_DELTA):
        self.p = patience; self.d = min_delta; self.best = None; self.bad = 0

    def step(self, v):
        if self.best is None or v < self.best - self.d:
            self.best = v; self.bad = 0
        else:
            self.bad += 1
        return self.bad >= self.p

### -------------------------------
### Training Backbones
### -------------------------------
def train_backbone_ann(model, t_train, y_train):
    model = model.to(DEVICE)
    opt = optim.Adam(model.parameters(), lr=LR, weight_decay=WD)
    es  = ES(); best, bestv = None, float("inf")
    for ep in range(1, MAX_EPOCHS+1):
        model.train(); opt.zero_grad()
        loss = nn_loss(model, t_train, y_train)
        loss.backward(); opt.step()
        v = float(loss.item())
        if v < bestv - MIN_DELTA:
            bestv = v; es.bad = 0; best = {k: w.detach().cpu().clone() for k, w in model.state_dict().items()}
        elif es.step(v): break
    if best: model.load_state_dict(best)
    return model.eval()

def train_backbone_pinn_fixed_col(model, t_train, y_train, t_col_fixed):
    model = model.to(DEVICE)
    opt = optim.Adam(model.parameters(), lr=LR, weight_decay=WD)
    es  = ES(); best, bestv = None, float("inf")
    for ep in range(1, MAX_EPOCHS+1):
        model.train(); opt.zero_grad()
        loss = pinn_total_loss_fixed(model, t_train, y_train, t_col_fixed)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        opt.step()
        v = float(loss.item())
        if v < bestv - MIN_DELTA:
            bestv = v; es.bad = 0; best = {k: w.detach().cpu().clone() for k, w in model.state_dict().items()}
        elif es.step(v): break
    if best: model.load_state_dict(best)
    return model.eval()

### -------------------------------
### Predictions (Single & Bagging)
### -------------------------------
@torch.no_grad()
def predict_deterministic(model):
    return model(t_eval).cpu().numpy().ravel()

def predict_uq_single(trained_model):
    uq = TestTimeBernoulliUQ(trained_model.net).to(DEVICE)
    samples = []
    for _ in range(T_MC):
        uq.set_p(random.uniform(*P_RANGE))
        with torch.no_grad():
            samples.append(uq(t_eval).cpu().numpy().ravel())
    S = np.stack(samples, 0)
    return S.mean(0), S.std(0, ddof=0)

@torch.no_grad()
def bagging_predict_deterministic(members):
    preds = [m(t_eval).cpu().numpy().ravel() for m in members]
    return np.mean(np.stack(preds, 0), 0)

def predict_uq_bagging(members):
    uq_members = [TestTimeBernoulliUQ(m.net).to(DEVICE) for m in members]
    bagged_samples = []
    for _ in range(T_MC):
        preds_m = []
        for uq in uq_members:
            uq.set_p(random.uniform(*P_RANGE))
            with torch.no_grad():
                preds_m.append(uq(t_eval).cpu().numpy().ravel())
        bagged_samples.append(np.mean(np.stack(preds_m, 0), axis=0))
    S = np.stack(bagged_samples, 0)
    return S.mean(0), S.std(0, ddof=0)

### -------------------------------
### Metrics
### -------------------------------
def mae(yhat, y): return float(np.mean(np.abs(yhat - y)))
def mse_np(yhat, y): return float(np.mean((yhat - y)**2))
def rmse(yhat, y): return float(np.sqrt(mse_np(yhat, y)))
def picp(mu, sd, y_true):
    lo, hi = mu - 1.96 * sd, mu + 1.96 * sd
    yt = y_true.ravel()
    return float(np.mean((yt >= lo) & (yt <= hi))) * 100  # Tính theo %

def mpiw(sd):
    return 2 * 1.96 * float(np.mean(sd))

### -------------------------------
### Main Execution: Compare All 4 Models
### -------------------------------
def main():
    print(f"=== SO SÁNH 4 MÔ HÌNH (IMPULSE NOISE: {int(CORRUPTION_RATE*100)}%, FACTOR: {IMPULSE_FACTOR}x MAX) ===")


    t_train, y_train = make_dataset()
    t_col_fixed = make_collocation_fixed()

    #  Train ANN (Single)
    print("Đang huấn luyện ANN...")
    ann_model = MLP()
    ann_model = train_backbone_ann(ann_model, t_train, y_train)

    #  Train PINN (Single)
    print("Đang huấn luyện PINN...")
    pinn_model = MLP()
    pinn_model = train_backbone_pinn_fixed_col(pinn_model, t_train, y_train, t_col_fixed)

    # Train Bagging PINN
    print(f"Đang huấn luyện Bagging PINN ({M_BAG} members)...")
    bagging_members = []
    t_train_np = t_train.cpu().numpy()
    y_train_np_t = y_train.cpu().numpy()

    for _ in range(M_BAG):

        t_b, y_b = bootstrap(t_train_np, y_train_np_t)
        t_b_t = torch.tensor(t_b, dtype=torch.float32, device=DEVICE)
        y_b_t = torch.tensor(y_b, dtype=torch.float32, device=DEVICE)
        t_c_m = make_collocation_fixed()

        model_m = MLP()
        model_m = train_backbone_pinn_fixed_col(model_m, t_b_t, y_b_t, t_c_m)
        bagging_members.append(model_m)

    # Train Init-Only PINN (Initialization-Only Ensemble / Deep Ensembles)
    print(f"Đang huấn luyện Init-Only PINN ({M_BAG} members)...")
    init_members = []

    for _ in range(M_BAG):
        model_init = MLP()

        model_init = train_backbone_pinn_fixed_col(model_init, t_train, y_train, t_col_fixed)
        init_members.append(model_init)

    # ---------------------------------------------------------
    # MAE, MSE, RMSE
    # ---------------------------------------------------------
    y_pred_ann  = predict_deterministic(ann_model)
    y_pred_pinn = predict_deterministic(pinn_model)
    y_pred_bag  = bagging_predict_deterministic(bagging_members)
    y_pred_init = bagging_predict_deterministic(init_members)

    # ---------------------------------------------------------
    # 7.Std
    # ---------------------------------------------------------

    y_mean_ann, y_std_ann   = predict_uq_single(ann_model)
    y_mean_pinn, y_std_pinn = predict_uq_single(pinn_model)
    y_mean_bag, y_std_bag   = predict_uq_bagging(bagging_members)
    y_mean_init, y_std_init = predict_uq_bagging(init_members)

    # ---------------------------------------------------------
    # 8. print
    # ---------------------------------------------------------
    y_true_flat = y_true_np.ravel()

    print("\n" + "="*115)
    print(f"{'MÔ HÌNH':<20} | {'MAE (Det)':<12} | {'MSE (Det)':<12} | {'RMSE (Det)':<12} | {'Mean Std':<10} | {'PICP (%)':<10} | {'MPIW'}")
    print("="*115)

    print(f"{'ANN':<20} | {mae(y_pred_ann, y_true_flat):<12.4f} | {mse_np(y_pred_ann, y_true_flat):<12.4f} | {rmse(y_pred_ann, y_true_flat):<12.4f} | {np.mean(y_std_ann):<10.4f} | {picp(y_mean_ann, y_std_ann, y_true_flat):<10.2f} | {mpiw(y_std_ann):.4f}")
    print("-" * 115)

    print(f"{'PINN':<20} | {mae(y_pred_pinn, y_true_flat):<12.4f} | {mse_np(y_pred_pinn, y_true_flat):<12.4f} | {rmse(y_pred_pinn, y_true_flat):<12.4f} | {np.mean(y_std_pinn):<10.4f} | {picp(y_mean_pinn, y_std_pinn, y_true_flat):<10.2f} | {mpiw(y_std_pinn):.4f}")
    print("-" * 115)

    print(f"{'Bagging PINN':<20} | {mae(y_pred_bag, y_true_flat):<12.4f} | {mse_np(y_pred_bag, y_true_flat):<12.4f} | {rmse(y_pred_bag, y_true_flat):<12.4f} | {np.mean(y_std_bag):<10.4f} | {picp(y_mean_bag, y_std_bag, y_true_flat):<10.2f} | {mpiw(y_std_bag):.4f}")
    print("-" * 115)

    print(f"{'Init-Only PINN':<20} | {mae(y_pred_init, y_true_flat):<12.4f} | {mse_np(y_pred_init, y_true_flat):<12.4f} | {rmse(y_pred_init, y_true_flat):<12.4f} | {np.mean(y_std_init):<10.4f} | {picp(y_mean_init, y_std_init, y_true_flat):<10.2f} | {mpiw(y_std_init):.4f}")
    print("="*115)

if __name__ == "__main__":
    main()