# -*- coding: utf-8 -*-
"""Ex1_sensitivity_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ewrC2DdmzN4TdcdN2kGAq8ipv5wqkeKb
"""

pip install optuna

import os
os.environ["TORCH_DISABLE_DYNAMO"] = "1"

import numpy as np, random, math
import torch, torch.nn as nn
import torch.optim as optim
import torch.autograd as autograd
import matplotlib.pyplot as plt
import os, math, random, time

# -------------------------------
# Repro & device
# -------------------------------
SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {DEVICE}")

### -------------------------------

k, y0 = 2.0, 1.5
T0, T1 = 0.0, 1.0
N_TRAIN = 100
N_COL   = 256

CORRUPTION_RATE = 0.05
IMPULSE_FACTOR  = 3

def exact_np(t):
    return y0 * np.exp(-k * t)

t_eval_np = np.linspace(T0, T1, 200)
t_eval = torch.tensor(t_eval_np, dtype=torch.float32, device=DEVICE).reshape(-1,1)
y_true_np = exact_np(t_eval_np)

def make_dataset():
    t_np = np.linspace(T0, T1, N_TRAIN)
    y_clean = exact_np(t_np)
    y_np = y_clean.copy()

    if CORRUPTION_RATE > 0:
        max_y = np.max(np.abs(y_clean))
        actual_impulse_mag = IMPULSE_FACTOR * max_y

        n_corrupt = int(N_TRAIN * CORRUPTION_RATE)
        corrupt_idx = np.random.choice(N_TRAIN, n_corrupt, replace=False)
        signs = np.random.choice([-1.0, 1.0], size=n_corrupt)
        y_np[corrupt_idx] = signs * actual_impulse_mag

    t = torch.tensor(t_np, dtype=torch.float32, device=DEVICE).reshape(-1,1)
    y = torch.tensor(y_np, dtype=torch.float32, device=DEVICE).reshape(-1,1)
    return t, y

IC_t = torch.zeros((1,1), dtype=torch.float32, device=DEVICE)
IC_y = torch.tensor([[y0]], dtype=torch.float32, device=DEVICE)

def bootstrap(t, y):
    n = len(t)
    idx = np.random.choice(n, size=n, replace=True)
    return t[idx], y[idx]

def make_collocation_fixed(n_col=N_COL):
    return (torch.rand((n_col,1), device=DEVICE) * (T1 - T0) + T0)


### -------------------------------
MAX_EPOCHS = 1000
PATIENCE   = 20
MIN_DELTA  = 1e-4
LR = 1e-3
WD = 0.0
LAMBDA_IC = 1.0; LAMBDA_PDE = 1.0; LAMBDA_DATA = 1.0

# MC-Dropout for UQ
P_RANGE = (0.2, 0.5)
T_MC    = 1000

class MLP(nn.Module):
    def __init__(self, in_dim=1, out_dim=1):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, 64), nn.Tanh(),
            nn.Linear(64, 64), nn.Tanh(),
            nn.Linear(64, out_dim)
        )
    def forward(self, x): return self.net(x)

class TestTimeBernoulliUQ(nn.Module):
    def __init__(self, core: nn.Sequential):
        super().__init__()
        self.core = core
        self.p = 0.3

    def set_p(self, p):
        self.p = float(p)

    def forward(self, x):
        out = x
        for m in self.core:
            out = m(out)
            if isinstance(m, (nn.Tanh, nn.ReLU, nn.GELU, nn.SiLU)):
                msk = (torch.rand_like(out) > self.p).float()
                out = out * msk / (1.0 - self.p + 1e-12)
        return out

mse = nn.MSELoss()

def pinn_residual(model, t):
    t.requires_grad_(True)
    y = model(t)
    dy = autograd.grad(y, t, torch.ones_like(y), create_graph=True)[0]
    return dy + k * y

def pinn_total_loss_fixed(model, t, y, t_col_fixed):
    l_data = mse(model(t), y)
    l_ic   = mse(model(IC_t), IC_y)
    res    = pinn_residual(model, t_col_fixed.requires_grad_(True))
    l_pde  = torch.mean(res**2)
    return LAMBDA_DATA * l_data + LAMBDA_IC * l_ic + LAMBDA_PDE * l_pde

class ES:
    def __init__(self):
        self.best = None; self.bad = 0
    def step(self, v):
        if self.best is None or v < self.best - MIN_DELTA:
            self.best = v; self.bad = 0
        else:
            self.bad += 1
        return self.bad >= PATIENCE

def train_member(t_train, y_train, t_col):
    model = MLP().to(DEVICE)
    opt = optim.Adam(model.parameters(), lr=LR, weight_decay=WD)
    es = ES(); best_state = None; best_v = float("inf")
    for _ in range(MAX_EPOCHS):
        model.train(); opt.zero_grad()
        loss = pinn_total_loss_fixed(model, t_train, y_train, t_col)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        opt.step()

        v = float(loss.item())
        if v < best_v - MIN_DELTA:
            best_v = v; es.bad = 0; best_state = {k: w.detach().cpu().clone() for k, w in model.state_dict().items()}
        elif es.step(v): break
    if best_state: model.load_state_dict(best_state)
    return model.eval()

### -------------------------------
### Det & UQ
### -------------------------------
@torch.no_grad()
def predict_bagging(members):
    preds = [m(t_eval).cpu().numpy().ravel() for m in members]
    return np.mean(np.stack(preds, 0), 0)

def predict_uq_bagging(members):
    uq_members = [TestTimeBernoulliUQ(m.net).to(DEVICE) for m in members]
    bagged_samples = []
    for _ in range(T_MC):
        preds_m = []
        for uq in uq_members:
            uq.set_p(random.uniform(*P_RANGE))
            with torch.no_grad():
                preds_m.append(uq(t_eval).cpu().numpy().ravel())
        bagged_samples.append(np.mean(np.stack(preds_m, 0), axis=0))
    S = np.stack(bagged_samples, 0)
    return S.mean(0), S.std(0, ddof=0)

# UQ 95% CI
def picp(mu, sd, y_true):
    lo, hi = mu - 1.96 * sd, mu + 1.96 * sd
    yt = y_true.ravel()
    return float(np.mean((yt >= lo) & (yt <= hi))) * 100

def mpiw(sd):
    return 2 * 1.96 * float(np.mean(sd))

def main():
    t_train, y_train = make_dataset()
    t_train_np = t_train.cpu().numpy()
    y_train_np = y_train.cpu().numpy()

    M_LIST = [1,2,5,10,20,50,100,200]
    bagging_members = []
    total_time = 0.0

    print("=== KHẢO SÁT ĐỘ NHẠY M - BAGGING PINN (VÍ DỤ 1) ===")
    print(f"{'M':<5} | {'Thời gian(s)':<13} | {'MAE (Det)':<10} | {'RMSE (Det)':<11} | {'PICP (%)':<10} | {'MPIW'}")
    print("-" * 80)

    for target_m in M_LIST:
        start_time = time.time()

        while len(bagging_members) < target_m:
            t_b, y_b = bootstrap(t_train_np, y_train_np)
            t_b_t = torch.tensor(t_b, dtype=torch.float32, device=DEVICE)
            y_b_t = torch.tensor(y_b, dtype=torch.float32, device=DEVICE)
            t_col_b = make_collocation_fixed()

            trained_model = train_member(t_b_t, y_b_t, t_col_b)
            bagging_members.append(trained_model)


        total_time += (time.time() - start_time)

        #  Deterministic
        y_pred_det = predict_bagging(bagging_members)
        mae = float(np.mean(np.abs(y_pred_det - y_true_np)))
        rmse_det = float(np.sqrt(np.mean((y_pred_det - y_true_np)**2)))

        # PICP và MPIW
        y_mean_uq, y_sd_uq = predict_uq_bagging(bagging_members)
        cr_val = picp(y_mean_uq, y_sd_uq, y_true_np)
        mpiw_val = mpiw(y_sd_uq)

        print(f"{target_m:<5} | {total_time:<13.2f} | {mae:<10.6f} | {rmse_det:<11.6f} | {cr_val:>6.2f}     | {mpiw_val:.6f}")

if __name__ == "__main__":
    main()

