# -*- coding: utf-8 -*-
"""EX2_impulsenoise_UQ

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Lb1mlEAwif9R7h4my--w4r6tUtbculy
"""

pip install optuna

import numpy as np, random, math
import torch, torch.nn as nn
import torch.optim as optim
import torch.autograd as autograd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401
from matplotlib import cm

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {DEVICE}")

### -------------------------------
### IMPULSE NOISE / OUTLIERS)
### -------------------------------
CORRUPTION_RATE = 0.05
IMPULSE_FACTOR  = 3

### -------------------------------
### Exact solution
### -------------------------------
def u_exact_np(x, t):
    return np.sin(np.pi * x) * np.cos(np.pi * t)

def u_exact_torch(x, t):
    return torch.sin(math.pi * x) * torch.cos(math.pi * t)

### -------------------------------
### Supervised set = 200 grid points
### -------------------------------
NX_SUP, NT_SUP = 20, 10
assert NX_SUP * NT_SUP == 200

def make_supervised_grid_dynamic_impulse(nx=NX_SUP, nt=NT_SUP):
    xs = np.linspace(0, 1, nx)
    ts = np.linspace(0, 1, nt)
    Xg, Tg = np.meshgrid(xs, ts, indexing="xy")
    X = np.c_[Xg.ravel(), Tg.ravel()].astype(np.float32)

    u_clean = u_exact_np(X[:,0:1], X[:,1:2])
    y_np = u_clean.copy()

    n_total = len(X)
    if CORRUPTION_RATE > 0:

        max_y = np.max(np.abs(u_clean))
        actual_impulse_mag = IMPULSE_FACTOR * max_y

        n_corrupt = int(n_total * CORRUPTION_RATE)
        corrupt_idx = np.random.choice(n_total, n_corrupt, replace=False)


        signs = np.random.choice([-1.0, 1.0], size=(n_corrupt, 1))
        y_np[corrupt_idx] = signs * actual_impulse_mag

    return X, y_np.astype(np.float32)

def make_clean_test_grid(nx=60, nt=60):
    xs = np.linspace(0, 1, nx)
    ts = np.linspace(0, 1, nt)
    Xg, Tg = np.meshgrid(xs, ts, indexing="xy")
    grid = np.c_[Xg.ravel(), Tg.ravel()].astype(np.float32)
    y_exact = u_exact_np(grid[:,0:1], grid[:,1:2]).ravel()
    return xs, ts, Xg, Tg, grid, y_exact

### -------------------------------
### Bagging Helper
### -------------------------------
def bootstrap(X, y):
    n = len(X)
    idx = np.random.choice(n, size=n, replace=True)
    return X[idx], y[idx]

### -------------------------------
### Hyperparameters
### -------------------------------
HIDDEN_LAYERS = 3
HIDDEN_WIDTH  = 128
ACT           = "tanh"

MAX_EPOCHS = 1000
PATIENCE   = 20
MIN_DELTA  = 1e-4
LR = 1e-3
WD = 0.0

LAMBDA_DATA = 1.0
LAMBDA_PDE  = 0.1
M_BAG   = 5
N_COL   = 1000

P_RANGE_TEST = (0.2, 0.5)
T_MC         = 1000

### -------------------------------
### Collocation: Chebyshev nodes + optional jitter
### -------------------------------
def make_collocation_fixed(n_col, jitter=0.0):
    def cheb_nodes_1d(n):
        k = np.arange(1, n+1)
        return 0.5 * (1 - np.cos(np.pi * (2 * k - 1) / (2 * n)))

    n1 = int(np.sqrt(n_col))
    n2 = n1
    xs = cheb_nodes_1d(n1)
    ts = cheb_nodes_1d(n2)
    X, T = np.meshgrid(xs, ts, indexing="xy")
    x = X.ravel()[:n_col]
    t = T.ravel()[:n_col]

    if jitter > 0:
        x = np.clip(x + np.random.uniform(-jitter, jitter, size=x.shape), 0, 1)
        t = np.clip(t + np.random.uniform(-jitter, jitter, size=t.shape), 0, 1)

    x = torch.tensor(x, dtype=torch.float32, device=DEVICE).view(-1,1)
    t = torch.tensor(t, dtype=torch.float32, device=DEVICE).view(-1,1)
    return x, t

### -------------------------------
### Models
### -------------------------------
def act(name):
    return {"tanh": nn.Tanh(), "relu": nn.ReLU(), "gelu": nn.GELU(), "silu": nn.SiLU()}[name]

class MLP(nn.Module):
    def __init__(self, in_dim=2, out_dim=1, L=HIDDEN_LAYERS, W=HIDDEN_WIDTH, act_name=ACT):
        super().__init__()
        A = act(act_name)
        layers = [nn.Linear(in_dim, W), A]
        for _ in range(L-1):
            layers += [nn.Linear(W, W), A]
        layers += [nn.Linear(W, out_dim)]
        self.net = nn.Sequential(*layers)

    def forward(self, xt):
        return self.net(xt)

class TestTimeBernoulliUQ(nn.Module):
    def __init__(self, core_sequential: nn.Sequential):
        super().__init__()
        self.core = core_sequential
        self.p = 0.3

    def set_p(self, p: float):
        self.p = float(p)

    def forward(self, xt):
        out = xt
        for m in self.core:
            out = m(out)
            if isinstance(m, (nn.Tanh, nn.ReLU, nn.GELU, nn.SiLU)):
                mask = (torch.rand_like(out) > self.p).float()
                out  = out * mask / (1.0 - self.p + 1e-12)
        return out

### -------------------------------
### Losses & residual (wave: u_tt - u_xx)
### -------------------------------
mse = nn.MSELoss()

def ann_loss(model, xt, u): return mse(model(xt), u)

def wave_residual(model, x, t):
    xt = torch.cat([x,t], dim=1)
    xt.requires_grad_(True)
    u  = model(xt)
    du = autograd.grad(u, xt, torch.ones_like(u), create_graph=True)[0]
    u_x = du[:,0:1]
    u_t = du[:,1:2]
    u_xx = autograd.grad(u_x, xt, torch.ones_like(u_x), create_graph=True)[0][:,0:1]
    u_tt = autograd.grad(u_t, xt, torch.ones_like(u_t), create_graph=True)[0][:,1:2]
    return u_tt - u_xx

def pinn_total_loss_fixed(model, xt_sup, u_sup, x_c_fixed, t_c_fixed):
    l_data = mse(model(xt_sup), u_sup)
    res    = wave_residual(model, x_c_fixed, t_c_fixed)
    l_pde  = torch.mean(res**2)
    return LAMBDA_DATA * l_data + LAMBDA_PDE * l_pde

### -------------------------------
### EarlyStopping & Helpers
### -------------------------------
class ES:
    def __init__(self, patience=PATIENCE, min_delta=MIN_DELTA):
        self.p = patience; self.d = min_delta; self.best = None; self.bad = 0
    def step(self, v):
        if self.best is None or v < self.best - self.d:
            self.best = v; self.bad = 0
        else:
            self.bad += 1
        return self.bad >= self.p

def to_torch_xy(X, y):
    xt = torch.tensor(X, dtype=torch.float32, device=DEVICE)
    u  = torch.tensor(y, dtype=torch.float32, device=DEVICE)
    return xt, u

### -------------------------------
### Training Backbones
### -------------------------------
def train_ann(model, Xsup, ysup, Xva, yva):
    model = model.to(DEVICE)
    xt_tr, u_tr = to_torch_xy(Xsup, ysup)
    xt_va, u_va = to_torch_xy(Xva, yva)
    opt = optim.Adam(model.parameters(), lr=LR, weight_decay=WD)
    es  = ES(); best, bestv = None, float("inf")

    for ep in range(1, MAX_EPOCHS+1):
        model.train(); opt.zero_grad()
        loss = ann_loss(model, xt_tr, u_tr)
        loss.backward(); opt.step()

        model.eval()
        with torch.no_grad():
            v = float(mse(model(xt_va), u_va).item())
            if v < bestv - MIN_DELTA:
                bestv = v; es.bad = 0; best = {k:w.detach().cpu().clone() for k,w in model.state_dict().items()}
            elif es.step(v): break
    if best is not None: model.load_state_dict(best)
    return model.eval()

def train_pinn_fixed_col(model, Xsup, ysup, Xva, yva, x_c_fixed, t_c_fixed):
    model = model.to(DEVICE)
    xt_tr, u_tr = to_torch_xy(Xsup, ysup)
    xt_va, u_va = to_torch_xy(Xva, yva)
    opt = optim.Adam(model.parameters(), lr=LR, weight_decay=WD)
    es  = ES(); best, bestv = None, float("inf")

    for ep in range(1, MAX_EPOCHS+1):
        model.train(); opt.zero_grad()
        loss = pinn_total_loss_fixed(model, xt_tr, u_tr, x_c_fixed, t_c_fixed)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        opt.step()

        model.eval()
        with torch.no_grad():
            v = float(mse(model(xt_va), u_va).item())
            if v < bestv - MIN_DELTA:
                bestv = v; es.bad = 0; best = {k:w.detach().cpu().clone() for k,w in model.state_dict().items()}
            elif es.step(v): break
    if best is not None: model.load_state_dict(best)
    return model.eval()

### -------------------------------
### Predict & Metrics
### -------------------------------
@torch.no_grad()
def predict_det(model, X):
    xt = torch.tensor(X, dtype=torch.float32, device=DEVICE)
    return model(xt).cpu().numpy().ravel()

@torch.no_grad()
def predict_det_bagging(members, X):
    preds = [predict_det(m, X) for m in members]
    return np.mean(np.stack(preds, 0), 0)

def mae_np(yhat, ytrue): return float(np.mean(np.abs(yhat - ytrue.ravel())))
def mse_np(yhat, ytrue): return float(np.mean((yhat - ytrue.ravel())**2))
def rmse_np(yhat, ytrue): return float(np.sqrt(mse_np(yhat, ytrue)))
def picp(mu, sd, y_true):
    lo, hi = mu - 1.96 * sd, mu + 1.96 * sd
    yt = y_true.ravel()
    return float(np.mean((yt >= lo) & (yt <= hi))) * 100  # Tính theo %

def mpiw(sd):
    return 2 * 1.96 * float(np.mean(sd))

def predict_uq_single(model, X_np):
    Xt = torch.tensor(X_np, dtype=torch.float32, device=DEVICE)
    uq = TestTimeBernoulliUQ(model.net).to(DEVICE)
    samples = []
    for _ in range(T_MC):
        uq.set_p(random.uniform(*P_RANGE_TEST))
        with torch.no_grad():
            samples.append(uq(Xt).cpu().numpy().ravel())
    S = np.stack(samples, 0)
    return S.mean(0), S.std(0, ddof=0)

def predict_uq_bagging(members, X_np):
    Xt = torch.tensor(X_np, dtype=torch.float32, device=DEVICE)
    uq_members = [TestTimeBernoulliUQ(m.net).to(DEVICE) for m in members]
    bagged = []
    for _ in range(T_MC):
        preds_m = []
        for uq in uq_members:
            uq.set_p(random.uniform(*P_RANGE_TEST))
            with torch.no_grad():
                preds_m.append(uq(Xt).cpu().numpy().ravel())
        bagged.append(np.mean(np.stack(preds_m, 0), 0))
    S = np.stack(bagged, 0)
    return S.mean(0), S.std(0, ddof=0)

### -------------------------------
### Main Execution: Compare All 4 Models
### -------------------------------
def main():
    print(f"=== SO SÁNH 4 MÔ HÌNH (Ex2) | IMPULSE NOISE: {int(CORRUPTION_RATE*100)}%, FACTOR: {IMPULSE_FACTOR}x MAX ===")


    Xsup, ysup = make_supervised_grid_dynamic_impulse()
    Xva, yva = Xsup, ysup


    xs_test, ts_test, Xg_test, Tg_test, grid_test, y_exact = make_clean_test_grid()

    # ==========================================
    # 1. Standard ANN
    # ==========================================
    print("\n[1/4] Training Standard ANN...")
    model_ann = MLP()
    trained_ann = train_ann(model_ann, Xsup, ysup, Xva, yva)
    y_pred_ann = predict_det(trained_ann, grid_test)
    y_mean_ann, y_std_ann = predict_uq_single(trained_ann, grid_test)

    # ==========================================
    # 2. Standard PINN
    # ==========================================
    print("[2/4] Training Standard PINN...")
    model_pinn = MLP()
    x_c_pinn, t_c_pinn = make_collocation_fixed(N_COL, jitter=0.0)
    trained_pinn = train_pinn_fixed_col(model_pinn, Xsup, ysup, Xva, yva, x_c_pinn, t_c_pinn)
    y_pred_pinn = predict_det(trained_pinn, grid_test)
    y_mean_pinn, y_std_pinn = predict_uq_single(trained_pinn, grid_test)

    # ==========================================
    # 3. Bagging PINN
    # ==========================================
    print("[3/4] Training Bagging PINN...")
    bagging_members = []
    for m in range(M_BAG):
        X_b, y_b = bootstrap(Xsup, ysup)

        x_c_b, t_c_b = make_collocation_fixed(N_COL, jitter=1e-3)

        model_b = MLP()
        bagging_members.append(train_pinn_fixed_col(model_b, X_b, y_b, Xva, yva, x_c_b, t_c_b))

    y_pred_bag = predict_det_bagging(bagging_members, grid_test)
    y_mean_bag, y_std_bag = predict_uq_bagging(bagging_members, grid_test)

    # ==========================================
    # 4. Initialization-Only Ensemble PINN
    # ==========================================
    print("[4/4] Training Initialization-Only Ensemble PINN...")
    init_members = []

    x_c_shared, t_c_shared = make_collocation_fixed(N_COL, jitter=0.0)
    for m in range(M_BAG):
        model_i = MLP()
        init_members.append(train_pinn_fixed_col(model_i, Xsup, ysup, Xva, yva, x_c_shared, t_c_shared))

    y_pred_init = predict_det_bagging(init_members, grid_test)
    y_mean_init, y_std_init = predict_uq_bagging(init_members, grid_test)


    # Print
    # ==========================================
    print("\n" + "="*115)
    print(f"{'MÔ HÌNH':<25} | {'MAE':<8} | {'MSE':<8} | {'RMSE':<8} | {'Mean Std':<10} | {'PICP (%)':<10} | {'MPIW'}")
    print("="*115)

    print(f"{'ANN (Det)':<25} | {mae_np(y_pred_ann, y_exact):.4f}   | {mse_np(y_pred_ann, y_exact):.4f}   | {rmse_np(y_pred_ann, y_exact):.4f}   | {'-':<10} | {'-':<10} | -")
    print(f"{'ANN (UQ Mean)':<25} | {mae_np(y_mean_ann, y_exact):.4f}   | {mse_np(y_mean_ann, y_exact):.4f}   | {rmse_np(y_mean_ann, y_exact):.4f}   | {np.mean(y_std_ann):<10.4f} | {picp(y_mean_ann, y_std_ann, y_exact):<10.2f} | {mpiw(y_std_ann):.4f}")
    print("-" * 115)

    print(f"{'PINN (Det)':<25} | {mae_np(y_pred_pinn, y_exact):.4f}   | {mse_np(y_pred_pinn, y_exact):.4f}   | {rmse_np(y_pred_pinn, y_exact):.4f}   | {'-':<10} | {'-':<10} | -")
    print(f"{'PINN (UQ Mean)':<25} | {mae_np(y_mean_pinn, y_exact):.4f}   | {mse_np(y_mean_pinn, y_exact):.4f}   | {rmse_np(y_mean_pinn, y_exact):.4f}   | {np.mean(y_std_pinn):<10.4f} | {picp(y_mean_pinn, y_std_pinn, y_exact):<10.2f} | {mpiw(y_std_pinn):.4f}")
    print("-" * 115)

    print(f"{'Bagging PINN (Det)':<25} | {mae_np(y_pred_bag, y_exact):.4f}   | {mse_np(y_pred_bag, y_exact):.4f}   | {rmse_np(y_pred_bag, y_exact):.4f}   | {'-':<10} | {'-':<10} | -")
    print(f"{'Bagging PINN (UQ Mean)':<25} | {mae_np(y_mean_bag, y_exact):.4f}   | {mse_np(y_mean_bag, y_exact):.4f}   | {rmse_np(y_mean_bag, y_exact):.4f}   | {np.mean(y_std_bag):<10.4f} | {picp(y_mean_bag, y_std_bag, y_exact):<10.2f} | {mpiw(y_std_bag):.4f}")
    print("-" * 115)

    print(f"{'Init-Only PINN (Det)':<25} | {mae_np(y_pred_init, y_exact):.4f}   | {mse_np(y_pred_init, y_exact):.4f}   | {rmse_np(y_pred_init, y_exact):.4f}   | {'-':<10} | {'-':<10} | -")
    print(f"{'Init-Only PINN (UQ)':<25} | {mae_np(y_mean_init, y_exact):.4f}   | {mse_np(y_mean_init, y_exact):.4f}   | {rmse_np(y_mean_init, y_exact):.4f}   | {np.mean(y_std_init):<10.4f} | {picp(y_mean_init, y_std_init, y_exact):<10.2f} | {mpiw(y_std_init):.4f}")
    print("="*115)

if __name__ == "__main__":
    main()

