# -*- coding: utf-8 -*-
"""Ex2_sensitivity_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bt1mcR6V2VuuFM23NCiKSIdEDOgVFTfh
"""

pip install optuna

import os, math, random, time
from google.colab import files
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.autograd as autograd
try:
    import optuna
except ImportError:
    raise ImportError("Please `pip install optuna` to run the hyperparameter search.")

import numpy as np, random, math
import torch, torch.nn as nn
import torch.optim as optim
import torch.autograd as autograd
import matplotlib.pyplot as plt

# -------------------------------
# Repro & device
# -------------------------------
SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {DEVICE}")


CORRUPTION_RATE = .05   # Level
IMPULSE_FACTOR  = 3    # Factor

def u_exact_np(x, t):
    return np.sin(np.pi * x) * np.cos(np.pi * t)

def make_supervised_grid_dynamic_impulse(nx=20, nt=10):
    xs = np.linspace(0, 1, nx)
    ts = np.linspace(0, 1, nt)
    Xg, Tg = np.meshgrid(xs, ts, indexing="xy")
    X = np.c_[Xg.ravel(), Tg.ravel()].astype(np.float32)

    u_clean = u_exact_np(X[:,0:1], X[:,1:2])
    y_np = u_clean.copy()

    n_total = len(X)
    if CORRUPTION_RATE > 0:
        max_y = np.max(np.abs(u_clean))
        actual_impulse_mag = IMPULSE_FACTOR * max_y

        n_corrupt = int(n_total * CORRUPTION_RATE)
        corrupt_idx = np.random.choice(n_total, n_corrupt, replace=False)

        signs = np.random.choice([-1.0, 1.0], size=(n_corrupt, 1))
        y_np[corrupt_idx] = signs * actual_impulse_mag

    return X, y_np.astype(np.float32)

def make_clean_test_grid(nx=60, nt=60):
    xs = np.linspace(0, 1, nx)
    ts = np.linspace(0, 1, nt)
    Xg, Tg = np.meshgrid(xs, ts, indexing="xy")
    grid = np.c_[Xg.ravel(), Tg.ravel()].astype(np.float32)
    y_exact = u_exact_np(grid[:,0:1], grid[:,1:2]).ravel()
    return xs, ts, Xg, Tg, grid, y_exact

def bootstrap(X, y):
    n = len(X)
    idx = np.random.choice(n, size=n, replace=True)
    return X[idx], y[idx]

def make_collocation_fixed(n_col=1000, jitter=0.0):
    def cheb_nodes_1d(n):
        k = np.arange(1, n+1)
        return 0.5 * (1 - np.cos(np.pi * (2 * k - 1) / (2 * n)))

    n1 = int(np.sqrt(n_col))
    xs = cheb_nodes_1d(n1); ts = cheb_nodes_1d(n1)
    X, T = np.meshgrid(xs, ts, indexing="xy")
    x = X.ravel()[:n_col]; t = T.ravel()[:n_col]

    if jitter > 0:
        x = np.clip(x + np.random.uniform(-jitter, jitter, size=x.shape), 0, 1)
        t = np.clip(t + np.random.uniform(-jitter, jitter, size=t.shape), 0, 1)

    x = torch.tensor(x, dtype=torch.float32, device=DEVICE).view(-1,1)
    t = torch.tensor(t, dtype=torch.float32, device=DEVICE).view(-1,1)
    return x, t

### -------------------------------
### -------------------------------
MAX_EPOCHS = 1000
PATIENCE   = 20
MIN_DELTA  = 1e-4
LR = 1e-3
LAMBDA_DATA = 1.0; LAMBDA_PDE = 0.1

P_RANGE_TEST = (0.2, 0.5)
T_MC         = 1000

class MLP(nn.Module):
    def __init__(self, in_dim=2, out_dim=1):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, 128), nn.Tanh(),
            nn.Linear(128, 128), nn.Tanh(),
            nn.Linear(128, 128), nn.Tanh(),
            nn.Linear(128, out_dim)
        )
    def forward(self, xt): return self.net(xt)

class TestTimeBernoulliUQ(nn.Module):
    def __init__(self, core_sequential: nn.Sequential):
        super().__init__()
        self.core = core_sequential
        self.p = 0.3

    def set_p(self, p: float):
        self.p = float(p)

    def forward(self, xt):
        out = xt
        for m in self.core:
            out = m(out)
            if isinstance(m, (nn.Tanh, nn.ReLU, nn.GELU, nn.SiLU)):
                mask = (torch.rand_like(out) > self.p).float()
                out  = out * mask / (1.0 - self.p + 1e-12)
        return out

mse = nn.MSELoss()

def wave_residual(model, x, t):
    xt = torch.cat([x,t], dim=1); xt.requires_grad_(True)
    u  = model(xt)
    du = autograd.grad(u, xt, torch.ones_like(u), create_graph=True)[0]
    u_x = du[:,0:1]; u_t = du[:,1:2]
    u_xx = autograd.grad(u_x, xt, torch.ones_like(u_x), create_graph=True)[0][:,0:1]
    u_tt = autograd.grad(u_t, xt, torch.ones_like(u_t), create_graph=True)[0][:,1:2]
    return u_tt - u_xx

def pinn_total_loss_fixed(model, xt_sup, u_sup, x_c, t_c):
    l_data = mse(model(xt_sup), u_sup)
    res    = wave_residual(model, x_c, t_c)
    l_pde  = torch.mean(res**2)
    return LAMBDA_DATA * l_data + LAMBDA_PDE * l_pde

class ES:
    def __init__(self):
        self.best = None; self.bad = 0
    def step(self, v):
        if self.best is None or v < self.best - MIN_DELTA:
            self.best = v; self.bad = 0
        else: self.bad += 1
        return self.bad >= PATIENCE

def train_member(Xsup, ysup, Xva, yva, x_c, t_c):
    model = MLP().to(DEVICE)
    xt_tr = torch.tensor(Xsup, dtype=torch.float32, device=DEVICE)
    u_tr  = torch.tensor(ysup, dtype=torch.float32, device=DEVICE)
    xt_va = torch.tensor(Xva, dtype=torch.float32, device=DEVICE)
    u_va  = torch.tensor(yva, dtype=torch.float32, device=DEVICE)

    opt = optim.Adam(model.parameters(), lr=LR)
    es = ES(); best_state = None; best_v = float("inf")

    for _ in range(1, MAX_EPOCHS + 1):
        model.train(); opt.zero_grad()
        loss = pinn_total_loss_fixed(model, xt_tr, u_tr, x_c, t_c)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        opt.step()

        model.eval()
        with torch.no_grad():
            v = float(mse(model(xt_va), u_va).item())
            if v < best_v - MIN_DELTA:
                best_v = v; es.bad = 0; best_state = {k:w.detach().cpu().clone() for k,w in model.state_dict().items()}
            elif es.step(v): break
    if best_state is not None: model.load_state_dict(best_state)
    return model.eval()

### -------------------------------
### Metrics
### -------------------------------
@torch.no_grad()
def predict_bagging(members, X):
    xt = torch.tensor(X, dtype=torch.float32, device=DEVICE)
    preds = [m(xt).cpu().numpy().ravel() for m in members]
    return np.mean(np.stack(preds, 0), 0)

def predict_uq_bagging(members, X_np):
    Xt = torch.tensor(X_np, dtype=torch.float32, device=DEVICE)
    uq_members = [TestTimeBernoulliUQ(m.net).to(DEVICE) for m in members]
    bagged = []
    for _ in range(T_MC):
        preds_m = []
        for uq in uq_members:
            uq.set_p(random.uniform(*P_RANGE_TEST))
            with torch.no_grad():
                preds_m.append(uq(Xt).cpu().numpy().ravel())
        bagged.append(np.mean(np.stack(preds_m, 0), 0))
    S = np.stack(bagged, 0)
    return S.mean(0), S.std(0, ddof=0)


def picp(mu, sd, y_true):
    lo, hi = mu - 1.96 * sd, mu + 1.96 * sd
    yt = y_true.ravel()
    return float(np.mean((yt >= lo) & (yt <= hi))) * 100

def mpiw(sd):
    return 2 * 1.96 * float(np.mean(sd))

def main():

    Xsup, ysup = make_supervised_grid_dynamic_impulse()
    Xva, yva = Xsup, ysup


    _, _, _, _, grid_test, y_exact = make_clean_test_grid()

    M_LIST = [1,2,5,10,20,50,100,200]
    bagging_members = []
    total_time = 0.0

    print("=== KHẢO SÁT ĐỘ NHẠY M - BAGGING PINN (VÍ DỤ 2) ===")
    print(f"{'M':<5} | {'Thời gian(s)':<13} | {'MAE (Det)':<10} | {'RMSE (Det)':<11} | {'PICP (%)':<10} | {'MPIW'}")
    print("-" * 80)

    for target_m in M_LIST:
        start_time = time.time()


        while len(bagging_members) < target_m:
            X_b, y_b = bootstrap(Xsup, ysup)

            x_c_b, t_c_b = make_collocation_fixed(1000, jitter=1e-3)
            trained_model = train_member(X_b, y_b, Xva, yva, x_c_b, t_c_b)
            bagging_members.append(trained_model)

        total_time += (time.time() - start_time)

        # Deterministic
        y_pred_det = predict_bagging(bagging_members, grid_test)
        mae = float(np.mean(np.abs(y_pred_det - y_exact)))
        rmse_det = float(np.sqrt(np.mean((y_pred_det - y_exact)**2)))

        #  PICP và MPIW
        y_mean_uq, y_sd_uq = predict_uq_bagging(bagging_members, grid_test)
        cr_val = picp(y_mean_uq, y_sd_uq, y_exact)
        mpiw_val = mpiw(y_sd_uq)

        print(f"{target_m:<5} | {total_time:<13.2f} | {mae:<10.6f} | {rmse_det:<11.6f} | {cr_val:>6.2f}     | {mpiw_val:.6f}")

if __name__ == "__main__":
    main()

